# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hospital_pb2 as hospital__pb2


class PatientServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAll = channel.unary_stream(
        '/PatientService/GetAll',
        request_serializer=hospital__pb2.PatientQuery.SerializeToString,
        response_deserializer=hospital__pb2.ResultsRecord.FromString,
        )


class PatientServiceServicer(object):

  def GetAll(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PatientServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAll': grpc.unary_stream_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=hospital__pb2.PatientQuery.FromString,
          response_serializer=hospital__pb2.ResultsRecord.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PatientService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DoctorServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAll = channel.unary_stream(
        '/DoctorService/GetAll',
        request_serializer=hospital__pb2.DoctorQuery.SerializeToString,
        response_deserializer=hospital__pb2.ResultsRecord.FromString,
        )


class DoctorServiceServicer(object):

  def GetAll(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DoctorServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAll': grpc.unary_stream_rpc_method_handler(
          servicer.GetAll,
          request_deserializer=hospital__pb2.DoctorQuery.FromString,
          response_serializer=hospital__pb2.ResultsRecord.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DoctorService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class LabServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddResult = channel.unary_unary(
        '/LabService/AddResult',
        request_serializer=hospital__pb2.ResultsRecord.SerializeToString,
        response_deserializer=hospital__pb2.BooleanResponse.FromString,
        )


class LabServiceServicer(object):

  def AddResult(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LabServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddResult': grpc.unary_unary_rpc_method_handler(
          servicer.AddResult,
          request_deserializer=hospital__pb2.ResultsRecord.FromString,
          response_serializer=hospital__pb2.BooleanResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'LabService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
